SET @bladeguard_threat_icon := COALESCE((
    SELECT `SpellIconID`
    FROM `spell_dbc`
    WHERE `ID` = 901073
), 146);

SET @bladeguard_threat_owned := (
    SELECT COUNT(*) = 1
    FROM `spell_dbc`
    WHERE `ID` = 901155
      AND `Name_Lang_enUS` = 'Bladeguard Threat'
      AND `Attributes` = 0x000000C0
      AND `AttributesEx4` = 0x00000040
      AND `DurationIndex` = 21
      AND `RangeIndex` = 1
      AND `CumulativeAura` = 1
      AND `SchoolMask` = 1
      AND `SpellClassSet` = 8
      AND `DispelType` = 0
      AND `EquippedItemClass` = -1
      AND `Effect_1` = 6
      AND `EffectDieSides_1` = 1
      AND `EffectBasePoints_1` = 74
      AND `EffectMiscValue_1` = 2
      AND `ImplicitTargetA_1` = 1
      AND `EffectAura_1` = 108
      AND `EffectSpellClassMaskA_1` = 0
      AND `EffectSpellClassMaskA_2` = 0
      AND `EffectSpellClassMaskA_3` = 0
      AND `SpellIconID` = @bladeguard_threat_icon
);

SET @bladeguard_threat_collision_guard := (
    SELECT `guard_row`
    FROM (
        SELECT 1 AS `guard_row`
        UNION ALL
        SELECT 2 FROM `spell_dbc`
        WHERE `ID` = 901155 AND @bladeguard_threat_owned = 0
        UNION ALL
        SELECT 3 FROM `wotlk_spells_full`
        WHERE `ID` = 901155 AND @bladeguard_threat_owned = 0
        UNION ALL
        SELECT 4 FROM `wotlk_spells`
        WHERE `ID` = 901155 AND @bladeguard_threat_owned = 0
    ) AS `collision_guard`
);

INSERT INTO `spell_dbc` (
    `ID`, `Attributes`, `AttributesEx4`, `DurationIndex`, `RangeIndex`,
    `CumulativeAura`, `SchoolMask`, `SpellClassSet`, `DispelType`,
    `EquippedItemClass`, `EquippedItemSubclass`, `EquippedItemInvTypes`,
    `Effect_1`, `EffectDieSides_1`, `EffectBasePoints_1`,
    `EffectMiscValue_1`, `ImplicitTargetA_1`, `EffectAura_1`,
    `EffectSpellClassMaskA_1`, `EffectSpellClassMaskA_2`,
    `EffectSpellClassMaskA_3`, `SpellIconID`, `Name_Lang_enUS`,
    `Description_Lang_enUS`, `AuraDescription_Lang_enUS`
) SELECT
    901155, 0x000000C0, 0x00000040, 21, 1,
    1, 1, 8, 0,
    -1, 0, 0,
    6, 1, 74,
    2, 1, 108,
    0, 0,
    0, @bladeguard_threat_icon, 'Bladeguard Threat',
    'Increases threat generated by Rogue abilities by 75%.',
    'Threat generated by Rogue abilities increased by 75%.'
FROM DUAL
WHERE @bladeguard_threat_owned = 0;

SET @bladeguard_threat_managed := (
    SELECT COUNT(*) = 1
    FROM `spell_dbc`
    WHERE `ID` = 901155
      AND `Name_Lang_enUS` = 'Bladeguard Threat'
      AND `Attributes` = 0x000000C0
      AND `AttributesEx4` = 0x00000040
      AND `DurationIndex` = 21
      AND `RangeIndex` = 1
      AND `CumulativeAura` = 1
      AND `SchoolMask` = 1
      AND `SpellClassSet` = 8
      AND `DispelType` = 0
      AND `EquippedItemClass` = -1
      AND `Effect_1` = 6
      AND `EffectDieSides_1` = 1
      AND `EffectBasePoints_1` = 74
      AND `EffectMiscValue_1` = 2
      AND `ImplicitTargetA_1` = 1
      AND `EffectAura_1` = 108
      AND `EffectSpellClassMaskA_1` = 0
      AND `EffectSpellClassMaskA_2` = 0
      AND `EffectSpellClassMaskA_3` = 0
      AND `SpellIconID` = @bladeguard_threat_icon
);

SET @bladeguard_passive_managed := (
    SELECT COUNT(*) = 1
    FROM `spell_dbc`
    WHERE `ID` = 901073
      AND `Name_Lang_enUS` = 'Bladeguard'
      AND `Attributes` = 0x00000040
      AND `SpellClassSet` = 8
      AND `EquippedItemClass` = 4
      AND `EquippedItemSubclass` = 64
      AND `EquippedItemInvTypes` = 16384
      AND `EffectAura_1` = 142
      AND `EffectAura_2` = 51
      AND `EffectAura_3` = 42
      AND `EffectTriggerSpell_3` = 901074
);

UPDATE `spell_dbc`
SET `Description_Lang_enUS` = 'While you have a shield equipped, increases armor from equipped items by $s1% and block chance by $s2%, and increases threat generated by Rogue abilities by 75%. Successful blocks restore 5 Energy. This can occur once per second.',
    `AuraDescription_Lang_enUS` = 'Armor from equipped items increased by $s1%, block chance increased by $s2%, and threat generated by Rogue abilities increased by 75%. Successful blocks restore Energy.'
WHERE `ID` = 901073
  AND @bladeguard_passive_managed = 1
  AND @bladeguard_threat_managed = 1;

DELETE FROM `spell_script_names`
WHERE `ScriptName` = 'spell_apoc_rogue_bladeguard';

INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`)
SELECT 901073, 'spell_apoc_rogue_bladeguard'
FROM DUAL
WHERE @bladeguard_passive_managed = 1
  AND @bladeguard_threat_managed = 1;

INSERT INTO `spell_custom_attr` (`spell_id`, `attributes`)
SELECT 901155, 0x01000000
FROM DUAL
WHERE @bladeguard_threat_managed = 1
ON DUPLICATE KEY UPDATE
    `attributes` = `spell_custom_attr`.`attributes` | VALUES(`attributes`);

INSERT INTO `wotlk_spells` (`ID`, `name`)
SELECT 901155, 'Bladeguard Threat'
FROM DUAL
WHERE @bladeguard_threat_managed = 1
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);
